url: "ruiawang.github.io"
baseurl: 
title: ruiawang
description: Rui Wang's Homepage
author: Rui Wang

permalink: /:slug/index.html

sass:
  style: compressed

exclude:
  - .gitignore
  - _config.yml
  - Gemfile
  - Gemfile.lock
  - README.md

collections:
  posts:
    output: true
  tags:
    output: true
    permalink: /tags/:slug/index.html
  whims:
    output: true
    permalink: /whims/:slug/index.html
  whim_tags:
    output: true
    permalink: /whims/tags/:slug/index.html

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  - scope:
      path: ""
      type: "whims"
    values:
      layout: "whim"
  - scope:
      path: ""
      type: "whim_tags"
    values:
      layout: "whim-tag"

markdown: kramdown
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]
  math_engine: katex
  input: GFM
  syntax_highlighter: rouge
  
highlighter: rouge